# Generated by Django 5.1.5 on 2025-02-07 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='STATE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('mobile', models.PositiveBigIntegerField()),
                ('Account_number', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhar', models.PositiveBigIntegerField()),
                ('father_name', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='profile_pics')),
                ('pin', models.IntegerField(blank=True, default=0)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender')),
                ('state', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
    ]
